# Generated by Django 3.2.4 on 2023-08-04 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactUs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactForm',
            new_name='ContactModel',
        ),
    ]
